% -------------------------------------------------------------------
%  Generated by MATLAB on 23-Nov-2023 17:01:44
%  MATLAB version: 9.13.0.2049777 (R2022b)
% -------------------------------------------------------------------
saveVarsMat = load('LS_4.mat');

A = ...
  [0 1;
   -2 -3];

B = ...
  [0 1;
   1 0];

C = [1 0];

D = [0 0];

ans = [-1; -2];

b = ...
  [0 1;
   1 0];

sys = saveVarsMat.sys; % <1x1 ss> unsupported class

clear saveVarsMat;
